#!/bin/bash

echo "=== Titanic ML Project - Remote Repository Setup ==="
echo ""
echo "To push this project to a remote repository, follow these steps:"
echo ""
echo "1. Go to GitHub.com and create a new repository:"
echo "   - Name: titanic-ml-project (or your preferred name)"
echo "   - Make it public or private as you prefer"
echo "   - DO NOT initialize with README, .gitignore, or license (we already have these)"
echo ""
echo "2. After creating the repository, GitHub will show you commands like:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Replace YOUR_USERNAME and YOUR_REPO_NAME with your actual values"
echo ""
echo "4. Run those commands in this directory"
echo ""
echo "Example:"
echo "   git remote add origin https://github.com/yourusername/titanic-ml-project.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "The repository is ready to be pushed once you add the remote origin!" 